#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            clientId: sample-app
#            clientSecret: 871f49ea-44f7-4d44-8f0e-04ed8f93719b

keycloak:
  realm: sample
  auth-server-url: https://keycloak.docker.internal/auth
#  ssl-required: external
  resource: sample-app
  public-client: false
  use-resource-role-mappings: true
  principal-attribute: preferred_username
  credentials:
    secret: 871f49ea-44f7-4d44-8f0e-04ed8f93719b

logging:
  level:
    org:
      springframework:
        security: debug
